import 'dotenv/config';

// Seeds the Blue Fleet demo account and a week of history for it.
//
//   npm run demo:seed              # add what is missing, touch nothing else
//   npm run demo:seed -- --fresh   # wipe Blue Fleet's history and start over
//
// Refuses to run against the production database: the account, its vehicles
// and its history exist only in the demo Neon database named in .env.demo.
//
// The default run is additive. It creates the account, drivers, vehicles and
// devices that do not exist yet and writes a week of history only for a
// vehicle that has none. Anything already on the account — a renamed
// company, a driver reassigned during a demo, a vehicle someone added, the
// password, the history — is left exactly as it is. Seed data must never
// overwrite what a person has done on an account. `--fresh` is the one
// exception, and it says so on the command line: it retires vehicles not in
// the profiles, resets the password and regenerates the whole week.
//
// History is generated by the same VehicleSimulator the live demo uses, so the
// routes on the trip-history map are the loops the cars will drive on the live
// map. Each vehicle works 08:00–19:00 and outside that reports the hourly
// parked heartbeat a real FMC150 sends, so the day/night pattern and the trip
// segmentation both look like a fleet rather than a screensaver.

import bcrypt from 'bcryptjs';
import { and, eq, inArray } from 'drizzle-orm';
import { db, initDatabase, closePool } from './db';
import {
  alerts,
  customers,
  deviceEvents,
  deviceFrames,
  devices,
  drivers,
  fuelPrices,
  fuelPurchases,
  telemetry,
  vehicles,
  virtualTanks,
} from './db/schema';
import {
  BLUE_FLEET_COMPANY,
  driverPin,
  BLUE_FLEET_EMAIL,
  BLUE_FLEET_PASSWORD,
  BLUE_FLEET_PROFILES,
  BlueFleetProfile,
  simulatorProfile,
} from './lib/blue-fleet';
// eslint-disable-next-line @typescript-eslint/no-require-imports
const { VehicleSimulator } = require('./lib/simulator');

const FRESH = process.argv.includes('--fresh');

const HISTORY_DAYS = 7;
/** One record every 30 s while a shift is running. */
const TICK_MS = 30_000;
/**
 * The simulator is told the true tick. An earlier version halved it to trim
 * the distance, which made every hop cover half what the recorded speed
 * implied — a thousand kilometres in sixty-one hours of driving. Distance is
 * now shaped honestly: city cruising speeds and longer rests between runs.
 */
const SIM_TICK_MS = TICK_MS;
/** Parked heartbeat cadence outside working hours, matching the real tracker. */
const HEARTBEAT_MS = 60 * 60_000;
/**
 * The simulator raises a green-driving event on a fixed share of moving ticks,
 * which at 30 s ticks is forty a day — every driver would score as reckless.
 * Each driver keeps a different share, so the safety scores spread out the way
 * a real fleet's do: the best a couple a day, the worst six or seven.
 */
const HARSH_KEEP_RATE = [0.05, 0.14, 0.07, 0.04, 0.16, 0.09, 0.12, 0.05, 0.15, 0.08];
const BENCHMARK_NGN_PER_LITER = 1280;

interface SimRecord {
  timestamp: number;
  eventId: number;
  gps: { latitude: number; longitude: number; speed: number; angle: number };
  meta: { fuelLevel: number; ignitionOn: boolean; speedKph: number; odometerKm: number };
  ioElements: Array<{ id: number; value: number }>;
}

function refuseProduction(): void {
  const url = process.env.DATABASE_URL ?? '';
  if (/rds\.amazonaws\.com/i.test(url) || /15432/.test(url)) {
    throw new Error(
      'DATABASE_URL points at production (RDS / the RDS tunnel). Blue Fleet lives in the demo database only — run with DOTENV_CONFIG_PATH=.env.demo'
    );
  }
  if (!/neon\.tech/i.test(url)) {
    throw new Error(`DATABASE_URL is not the Neon demo database — refusing (${url.replace(/:[^:@]+@/, ':***@')})`);
  }
}

async function upsertAccount() {
  let [customer] = await db
    .select({ id: customers.id })
    .from(customers)
    .where(eq(customers.email, BLUE_FLEET_EMAIL));
  if (!customer) {
    [customer] = await db
      .insert(customers)
      .values({
        name: 'Blue Fleet Operations',
        email: BLUE_FLEET_EMAIL,
        passwordHash: await bcrypt.hash(BLUE_FLEET_PASSWORD, 12),
        companyName: BLUE_FLEET_COMPANY,
        onboardingCompleted: true,
        // The product calls itself Blue Fleet for this account — the demo
        // is shown as the prospect's own tool.
        whiteLabel: true,
      })
      .returning({ id: customers.id });
    console.log(`created customer ${BLUE_FLEET_COMPANY}`);
  } else if (FRESH) {
    await db
      .update(customers)
      .set({ passwordHash: await bcrypt.hash(BLUE_FLEET_PASSWORD, 12), onboardingCompleted: true, whiteLabel: true })
      .where(eq(customers.id, customer.id));
    console.log(`customer ${BLUE_FLEET_COMPANY} exists — password reset to the documented one (--fresh)`);
  } else {
    console.log(`customer ${BLUE_FLEET_COMPANY} exists — left as is`);
  }
  return customer.id;
}

async function upsertVehicle(customerId: string, p: BlueFleetProfile) {
  const pinHash = await bcrypt.hash(driverPin(p.driver.code), 12);
  let [driver] = await db
    .select({ id: drivers.id })
    .from(drivers)
    .where(and(eq(drivers.customerId, customerId), eq(drivers.driverCode, p.driver.code)));
  if (!driver) {
    [driver] = await db
      .insert(drivers)
      .values({
        customerId,
        fullName: p.driver.name,
        phone: p.driver.phone,
        licenseNumber: p.driver.licence,
        driverCode: p.driver.code,
        pinHash,
        status: 'active',
      })
      .returning({ id: drivers.id });
  } else if (FRESH) {
    // A rename in the profiles reaches an existing driver only on --fresh;
    // a name someone changed on the account is otherwise theirs to keep.
    await db
      .update(drivers)
      .set({ fullName: p.driver.name, phone: p.driver.phone, licenseNumber: p.driver.licence, pinHash })
      .where(eq(drivers.id, driver.id));
  }

  let created = false;
  let [vehicle] = await db
    .select({ id: vehicles.id })
    .from(vehicles)
    .where(and(eq(vehicles.customerId, customerId), eq(vehicles.licensePlate, p.label)));
  if (!vehicle) {
    [vehicle] = await db
      .insert(vehicles)
      .values({
        customerId,
        licensePlate: p.label,
        make: p.make,
        model: p.model,
        year: p.year,
        vehicleType: p.vehicleType,
        tankCapacityLiters: p.tankCapacity,
        driverId: driver.id,
        driverName: p.driver.name,
      })
      .returning({ id: vehicles.id });
    created = true;
  } else if (FRESH) {
    await db
      .update(vehicles)
      .set({
        driverId: driver.id,
        driverName: p.driver.name,
        make: p.make,
        model: p.model,
        year: p.year,
        vehicleType: p.vehicleType,
        tankCapacityLiters: p.tankCapacity,
      })
      .where(eq(vehicles.id, vehicle.id));
  }

  const patch = { vehicleId: vehicle.id, customerId, isActive: true, deviceModel: 'FMC130' };
  const [existing] = await db.select({ imei: devices.imei }).from(devices).where(eq(devices.imei, p.imei));
  if (!existing) await db.insert(devices).values({ imei: p.imei, ...patch });
  else if (FRESH) await db.update(devices).set(patch).where(eq(devices.imei, p.imei));

  return { vehicleId: vehicle.id, driverId: driver.id, created };
}

async function writeHistory(customerId: string, vehicleId: string, p: BlueFleetProfile) {
  // Every profile is a fresh simulator: the odometer starts at the profile's
  // figure and grows through the week, so the odometer on screen is the sum
  // of the distance actually drawn.
  const sim = new VehicleSimulator({ ...simulatorProfile(p), tickIntervalMs: SIM_TICK_MS });
  const end = Date.now();
  const start = end - HISTORY_DAYS * 24 * 3600_000;

  const rows: Array<typeof telemetry.$inferInsert> = [];
  const events: Array<typeof deviceEvents.$inferInsert> = [];
  let refuels = 0;
  let prevFuel = p.initialFuel;
  let t = start;

  while (t < end) {
    if (!sim.onShift(t)) {
      // Parked for the night: one heartbeat an hour, the way the real
      // tracker reports, and the simulator's clock is stepped past it.
      sim.nextRecord(t);
      rows.push({
        imei: p.imei,
        customerId,
        vehicleId,
        recordedAt: new Date(t),
        fuelLevelLiters: sim.fuelLevel.toFixed(2),
        fuelSource: 'CAN',
        odometerKm: Math.round(sim.odometerKm),
        odometerM: Math.round(sim.odometerKm * 1000),
        latitude: sim.lat.toFixed(8),
        longitude: sim.lng.toFixed(8),
        speedKph: 0,
        ignitionOn: false,
      });
      t += HEARTBEAT_MS;
      continue;
    }

    const rec = sim.nextRecord(t) as SimRecord | null;
    if (!rec) break;

    rows.push({
      imei: p.imei,
      customerId,
      vehicleId,
      recordedAt: new Date(t),
      fuelLevelLiters: rec.meta.fuelLevel.toFixed(2),
      fuelSource: 'CAN',
      odometerKm: rec.meta.odometerKm,
      odometerM: rec.meta.odometerKm * 1000,
      latitude: rec.gps.latitude.toFixed(8),
      longitude: rec.gps.longitude.toFixed(8),
      speedKph: rec.meta.speedKph,
      ignitionOn: rec.meta.ignitionOn,
    });

    // A fill the simulator performed becomes a receipt the driver logged.
    if (rec.meta.fuelLevel - prevFuel > 10) {
      const liters = Math.round((rec.meta.fuelLevel - prevFuel) * 10) / 10;
      const price = BENCHMARK_NGN_PER_LITER + Math.round((Math.random() - 0.5) * 80);
      await db.insert(fuelPurchases).values({
        customerId,
        vehicleId,
        purchasedAt: new Date(t),
        merchant: [
          'TotalEnergies Wuse 2',
          'NNPC Mega Station, CBD',
          'AA Rano, Kubwa Expressway',
          'Conoil Garki',
          'Shema Mabushi',
          'Oando Asokoro',
        ][(BLUE_FLEET_PROFILES.indexOf(p) + refuels) % 6],
        litersDeclared: liters.toFixed(2),
        costPerLiterNgn: price,
        totalAmountNgn: Math.round(liters * price),
        odometerKm: rec.meta.odometerKm,
        status: 'verified',
        source: 'receipt',
      });
      refuels += 1;
    }
    prevFuel = rec.meta.fuelLevel;

    // Scenario events the simulator raised ride into device_events, the same
    // rows the decoder writes for a real tracker.
    if (rec.eventId === 253 && Math.random() < HARSH_KEEP_RATE[BLUE_FLEET_PROFILES.indexOf(p)]) {
      const type = rec.ioElements.find((e) => e.id === 253)?.value ?? 1;
      const g = (rec.ioElements.find((e) => e.id === 254)?.value ?? 30) / 100;
      events.push({
        imei: p.imei,
        customerId,
        vehicleId,
        eventType: type === 1 ? 'harsh_acceleration' : type === 2 ? 'harsh_braking' : 'harsh_cornering',
        severity: g >= 0.45 ? 'high' : 'medium',
        value: (g * 9.81).toFixed(2),
        unit: 'm/s2',
        speedKph: rec.meta.speedKph,
        latitude: rec.gps.latitude.toFixed(8),
        longitude: rec.gps.longitude.toFixed(8),
        occurredAt: new Date(t),
      });
    } else if (rec.eventId === 255 && Math.random() < HARSH_KEEP_RATE[BLUE_FLEET_PROFILES.indexOf(p)] / 2) {
      events.push({
        imei: p.imei,
        customerId,
        vehicleId,
        eventType: 'overspeeding',
        severity: 'medium',
        value: String(rec.meta.speedKph),
        unit: 'km/h',
        speedKph: rec.meta.speedKph,
        latitude: rec.gps.latitude.toFixed(8),
        longitude: rec.gps.longitude.toFixed(8),
        occurredAt: new Date(t),
      });
    }

    t += TICK_MS;
  }

  for (let i = 0; i < rows.length; i += 1000) {
    await db.insert(telemetry).values(rows.slice(i, i + 1000));
  }
  if (events.length) await db.insert(deviceEvents).values(events);

  await db
    .update(devices)
    .set({ lastSeenAt: new Date(rows[rows.length - 1].recordedAt as Date) })
    .where(eq(devices.imei, p.imei));

  const onHours = (rows.filter((r) => r.ignitionOn).length * TICK_MS) / 3_600_000;
  return {
    rows: rows.length,
    events: events.length,
    refuels,
    km: Math.round(sim.odometerKm - p.initialOdometer),
    onHours: Math.round(onHours * 10) / 10,
  };
}

const seed = async (): Promise<void> => {
  refuseProduction();
  await initDatabase();

  const customerId = await upsertAccount();
  const ids: Array<{ p: BlueFleetProfile; vehicleId: string }> = [];
  let createdCount = 0;
  for (const p of BLUE_FLEET_PROFILES) {
    const { vehicleId, created } = await upsertVehicle(customerId, p);
    ids.push({ p, vehicleId });
    if (created) createdCount += 1;
  }
  console.log(`${ids.length} vehicles, drivers and devices in place (${createdCount} created)`);

  // Anything of Blue Fleet's that is not in the profile list any more —
  // a plate renamed, a car dropped — goes, with everything hanging off it.
  // Only on --fresh: a vehicle someone added to the account is theirs.
  const keepPlates = BLUE_FLEET_PROFILES.map((p) => p.label);
  const stale = await db
    .select({ id: vehicles.id, plate: vehicles.licensePlate })
    .from(vehicles)
    .where(eq(vehicles.customerId, customerId));
  const staleIds = FRESH ? stale.filter((v) => !keepPlates.includes(v.plate)).map((v) => v.id) : [];
  if (staleIds.length) {
    // Their devices may already have been re-pointed at the new plates, so
    // frames are found through the telemetry rows they reference.
    await db.delete(deviceFrames).where(
      inArray(
        deviceFrames.telemetryId,
        db.select({ id: telemetry.id }).from(telemetry).where(inArray(telemetry.vehicleId, staleIds))
      )
    );
    await db.delete(telemetry).where(inArray(telemetry.vehicleId, staleIds));
    await db.delete(deviceEvents).where(inArray(deviceEvents.vehicleId, staleIds));
    await db.delete(fuelPurchases).where(inArray(fuelPurchases.vehicleId, staleIds));
    await db.delete(alerts).where(inArray(alerts.vehicleId, staleIds));
    await db.delete(virtualTanks).where(inArray(virtualTanks.vehicleId, staleIds));
    await db.delete(devices).where(inArray(devices.vehicleId, staleIds));
    await db.delete(vehicles).where(inArray(vehicles.id, staleIds));
    console.log(`retired ${staleIds.length} vehicle(s) no longer in the profiles`);
  }

  // Which vehicles get a generated week: on --fresh all of them, after a
  // wipe; otherwise only those with no telemetry at all.
  const vehicleIds = ids.map((v) => v.vehicleId);
  let targets = [...ids];
  if (!FRESH) {
    const withRows = new Set(
      (
        await db
          .selectDistinct({ vehicleId: telemetry.vehicleId })
          .from(telemetry)
          .where(inArray(telemetry.vehicleId, vehicleIds))
      ).map((r) => r.vehicleId)
    );
    targets = ids.filter((v) => !withRows.has(v.vehicleId));
  }
  if (targets.length === 0) {
    console.log('every vehicle already has history — nothing generated (use --fresh to regenerate)');
    console.log(`  Login:   ${BLUE_FLEET_EMAIL} / ${BLUE_FLEET_PASSWORD}`);
    return;
  }
  const targetIds = targets.map((v) => v.vehicleId);
  // Wipe only what is about to be regenerated.
  ids.length = 0;
  ids.push(...targets);
  vehicleIds.length = 0;
  vehicleIds.push(...targetIds);
  // Frames first: on an unpartitioned database they still hold a foreign key
  // to the telemetry row they came with.
  await db.delete(deviceFrames).where(inArray(deviceFrames.imei, ids.map((v) => v.p.imei)));
  await db.delete(deviceFrames).where(
    inArray(
      deviceFrames.telemetryId,
      db.select({ id: telemetry.id }).from(telemetry).where(inArray(telemetry.vehicleId, vehicleIds))
    )
  );
  await db.delete(telemetry).where(inArray(telemetry.vehicleId, vehicleIds));
  await db.delete(deviceEvents).where(inArray(deviceEvents.vehicleId, vehicleIds));
  await db.delete(fuelPurchases).where(inArray(fuelPurchases.vehicleId, vehicleIds));
  await db.delete(alerts).where(inArray(alerts.vehicleId, vehicleIds));
  await db.delete(virtualTanks).where(inArray(virtualTanks.vehicleId, vehicleIds));

  const [price] = await db
    .select({ id: fuelPrices.id })
    .from(fuelPrices)
    .where(eq(fuelPrices.customerId, customerId))
    .limit(1);
  if (!price) {
    await db.insert(fuelPrices).values({
      customerId,
      ngnPerLiter: String(BENCHMARK_NGN_PER_LITER),
      effectiveFrom: new Date(Date.now() - HISTORY_DAYS * 24 * 3600_000),
      source: 'manager',
      note: 'Demo benchmark',
    });
  }

  let total = { rows: 0, events: 0, refuels: 0 };
  for (const { p, vehicleId } of ids) {
    const r = await writeHistory(customerId, vehicleId, p);
    total = { rows: total.rows + r.rows, events: total.events + r.events, refuels: total.refuels + r.refuels };
    console.log(
      `  ${p.label.padEnd(11)} ${p.model.padEnd(9)} ${String(r.rows).padStart(5)} rows  ${String(r.km).padStart(4)} km  ` +
        `${String(r.onHours).padStart(5)} h on  ${Math.round(r.km / r.onHours)} km/h avg  ${r.events} events  ${r.refuels} receipts`
    );
  }

  console.log(`\nBlue Fleet ready: ${total.rows} telemetry rows, ${total.events} driving events, ${total.refuels} receipts over ${HISTORY_DAYS} days`);
  console.log(`  Login:   ${BLUE_FLEET_EMAIL} / ${BLUE_FLEET_PASSWORD}`);
  console.log('  Drivers:');
  for (const p of BLUE_FLEET_PROFILES) console.log(`    ${p.driver.code}  PIN ${driverPin(p.driver.code)}  ${p.driver.name.padEnd(18)} ${p.label}`);
};

seed()
  .catch((error) => {
    console.error('seed-blue-fleet failed:', (error as Error).message);
    process.exitCode = 1;
  })
  .finally(() => closePool());
